import {
  defineToolcraftPerformance,
  type ToolcraftPerformanceConfig,
} from "@/toolcraft/runtime";

const watercolorCanvasSelector = '[data-toolcraft-watercolor-canvas="true"]';
const mixingAreaSelector = '[data-toolcraft-mixing-area="true"] canvas';

const largeCanvasWorkloadFixture = {
  kind: "large-canvas" as const,
  loadProfile: {
    hardLimit: { height: 2160, renderScale: 2, width: 3840 },
    metric: "canvas-area" as const,
    smoothTarget: { height: 2160, renderScale: 2, width: 3840 },
    smoothTargetRatio: 1,
    target: "canvas.renderScale",
    userFacingRange: "fully-guaranteed" as const,
  },
  reason:
    "Largest working canvas size (3840x2160, Resolution scale 2) is the independent heavy baseline every workload control scenario is measured against.",
  value: { height: 2160, renderScale: 2, width: 3840 },
};

function controlDragScenario({
  automatedTestName,
  browserTestName,
  controlLabel,
  fixtureNote,
  id,
  target,
}: {
  automatedTestName: string;
  browserTestName: string;
  controlLabel: string;
  fixtureNote: string;
  id: string;
  target: string;
}) {
  return {
    automated: true,
    automatedTestName,
    browser: true,
    browserTestName,
    budget: { maxFrameGapMs: 100, maxInteractionMs: 200 },
    controlLabel,
    expectedObservable: `Dragging ${controlLabel} updates the slider thumb live and applies to the next stroke without freezing pointer input.`,
    fixture: fixtureNote,
    id,
    interaction: "control-drag" as const,
    target,
    uiSelector: watercolorCanvasSelector,
    workload: false,
  };
}

function controlChangeScenario({
  automatedTestName,
  browserTestName,
  expectedObservable,
  fixtureNote,
  id,
  target,
  uiSelector = watercolorCanvasSelector,
}: {
  automatedTestName: string;
  browserTestName: string;
  expectedObservable: string;
  fixtureNote: string;
  id: string;
  target: string;
  uiSelector?: string;
}) {
  return {
    automated: true,
    automatedTestName,
    browser: true,
    browserTestName,
    budget: { maxFrameGapMs: 100, maxInteractionMs: 250 },
    expectedObservable,
    fixture: fixtureNote,
    id,
    interaction: "control-change" as const,
    target,
    uiSelector,
    workload: false,
  };
}

export const appPerformance: ToolcraftPerformanceConfig = defineToolcraftPerformance({
  browserCheckPolicy: {
    fallbackRunner: "playwright",
    fallbackWhen: ["agent-browser-unavailable", "ci"],
    preferredRunner: "agent-browser",
  },
  rendererPipeline: {
    interactionInvalidation: [
      {
        interaction: "control-drag",
        invalidates: ["simulation-step", "preview-composite"],
        mustNotInvalidate: ["export-pixel-readback", "export-encode"],
        targets: [
          "canvas.renderScale",
          "brush.size",
          "paper.roughness",
          "paper.reliefHeight",
          "paper.dryingSpeed",
          "dynamics.wetnessSpread",
          "dynamics.granulation",
          "dynamics.edgeDarkening",
          "dynamics.pigmentOpacity",
        ],
      },
      {
        interaction: "control-change",
        invalidates: ["simulation-step", "preview-composite"],
        mustNotInvalidate: ["export-pixel-readback", "export-encode"],
        targets: [
          "canvas.size.width",
          "canvas.size.height",
          "brush.type",
          "brush.hairType",
          "paint.currentPigmentColor",
          "brush.waterCharge",
          "paint.mixingArea",
          "canvas.paintLayer",
          "export.image.resolution",
          "export.image.format",
        ],
      },
      {
        interaction: "animation-frame",
        invalidates: ["simulation-step", "preview-composite"],
        targets: [
          "paper.dryingSpeed",
          "dynamics.wetnessSpread",
          "dynamics.granulation",
          "dynamics.edgeDarkening",
        ],
      },
      {
        interaction: "viewport-drag",
        invalidates: [],
        mustNotInvalidate: [
          "simulation-step",
          "preview-composite",
          "export-pixel-readback",
          "export-encode",
        ],
        targets: ["canvas.viewport"],
      },
      {
        interaction: "viewport-zoom",
        invalidates: [],
        mustNotInvalidate: [
          "simulation-step",
          "preview-composite",
          "export-pixel-readback",
          "export-encode",
        ],
        targets: ["canvas.viewport"],
      },
      {
        interaction: "export",
        invalidates: ["export-pixel-readback", "export-encode"],
        targets: ["export.image.resolution", "export.image.format"],
      },
    ],
    passes: [
      {
        cacheKey: ["canvas.size.width", "canvas.size.height", "canvas.renderScale"],
        id: "simulation-step",
        inputs: [
          "previous-simulation-state",
          "brush-uniforms",
          "dynamics-uniforms",
          "paper-uniforms",
        ],
        invalidatedBy: ["control-drag", "control-change", "animation-frame"],
        kind: "composite",
        output: "intermediate",
        quality: "full",
        runsOn: "gpu",
      },
      {
        cacheKey: ["canvas.size.width", "canvas.size.height", "canvas.renderScale"],
        id: "preview-composite",
        inputs: ["simulation-step", "paper-uniforms"],
        invalidatedBy: ["animation-frame"],
        kind: "composite",
        output: "preview",
        quality: "preview",
        runsOn: "gpu",
      },
      {
        cacheKey: ["export.image.resolution"],
        id: "export-pixel-readback",
        inputs: ["preview-composite"],
        invalidatedBy: ["export"],
        kind: "pixel-transform",
        output: "export",
        quality: "export",
        runsOn: "export-only",
      },
      {
        id: "export-encode",
        inputs: ["export-pixel-readback"],
        invalidatedBy: ["export"],
        kind: "export",
        output: "export",
        quality: "export",
        runsOn: "export-only",
      },
    ],
  },
  rendererStrategy: "webgl",
  rendererTechnique: {
    exportRenderer: "webgl",
    fidelityRisks: [
      "The paper heightmap is a lightweight procedural value-noise approximation, not a scanned paper texture, so fine relief detail is stylized rather than photorealistic.",
    ],
    layers: [
      {
        content: ["shader", "noise", "bitmap-media"],
        exportMode: "included",
        id: "watercolour-simulation",
        kind: "product-foreground",
        primitiveCount: "high",
        renderer: "webgl",
        uiSelector: watercolorCanvasSelector,
      },
    ],
    performanceRisks: [
      "Large canvas sizes combined with Resolution scale 2 increase per-frame diffusion/evaporation pass cost across every backing texel.",
      "Export readback at 8K resolution performs a full-resolution GPU pixel readback plus a 2D canvas draw/encode step, which is a one-shot cost outside the live interactive loop.",
    ],
    previewRenderer: "webgl",
    productRepresentation: "pixel",
    rendererStrategy: "webgl",
    rendererWorkload: "pixel-output",
    sourceRepresentation: "procedural-data",
    whyNotAlternativeStrategies: [
      "The product is a continuous per-pixel wetness/pigment diffusion, evaporation, granulation, and edge-darkening simulation recomputed every animation frame across the full editable-output canvas (rendererWorkload pixel-output). Canvas 2D would require CPU-side convolution over every texel each frame, which cannot sustain interactive brush dragging at practical canvas sizes; WebGL2 fragment shaders parallelize that same per-pixel work on the GPU. Text-output and vector-output strategies do not apply because the product is raster pigment simulation, not text or vector geometry. Export reuses the same webgl rendererStrategy/exportRenderer as preview (previewRenderer) so exported pixels match the on-screen simulation state; only the read-back-and-encode step runs on the CPU via a 2D canvas for product-quality PNG bytes.",
    ],
  },
  rendererWorkload: "pixel-output",
  scenarios: [
    {
      automated: true,
      automatedTestName: "perf: watercolour-simulation-preview-render scenario is well-formed",
      browser: true,
      browserTestName: "browser perf: watercolour simulation stays smooth at max canvas size",
      budget: { maxFrameGapMs: 100, maxLongTaskMs: 220, maxPreviewMs: 500 },
      expectedObservable:
        "Composited paper and pigment pixels keep updating every animation frame, and a dragged brush stroke keeps producing visible pigment, at the largest working canvas size with Resolution scale 2.",
      fixture: "Canvas resized to 3840x2160 with Resolution scale set to 2, then a brush stroke is dragged.",
      id: "watercolour-simulation-preview-render",
      interaction: "preview-render",
      stress: true,
      stressFixture: {
        kind: "large-canvas",
        loadProfile: {
          hardLimit: { height: 2160, renderScale: 2, width: 3840 },
          metric: "canvas-area",
          smoothTarget: { height: 2160, renderScale: 2, width: 3840 },
          smoothTargetRatio: 1,
          target: "canvas.renderScale",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "3840x2160 at Resolution scale 2 (7680x4320 backing pixels) is the largest practical interactive working size the app exposes before export-only upscaling; this is the heaviest realistic per-frame simulation workload.",
        value: { height: 2160, renderScale: 2, width: 3840 },
      },
      uiSelector: watercolorCanvasSelector,
      values: {
        default: { height: 1080, renderScale: 2, width: 1920 },
        max: { height: 2160, renderScale: 2, width: 3840 },
        min: { height: 1080, renderScale: 1, width: 1920 },
      },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: brush-size-control-drag scenario is well-formed",
      browser: true,
      browserTestName: "browser perf: brush size drag stays responsive at max size",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 200 },
      controlLabel: "Size",
      expectedObservable:
        "Dragging Brush size to its maximum and drawing a stroke keeps the stamp deposit live and responsive without freezing pointer input.",
      fixture: "Largest working canvas size, brush size slider dragged to maximum, then a stroke is drawn.",
      id: "brush-size-control-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: 10,
          metric: "numeric-max",
          smoothTarget: 10,
          smoothTargetRatio: 1,
          target: "brush.size",
          userFacingRange: "fully-guaranteed",
        },
        reason: "10 is the largest brush size the app exposes.",
        value: 10,
      },
      target: "brush.size",
      uiSelector: watercolorCanvasSelector,
      values: { default: 4, max: 10, min: 0 },
      workload: true,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: render-scale-control-drag scenario is well-formed",
      browser: true,
      browserTestName: "browser perf: resolution scale drag stays responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 200 },
      controlLabel: "Resolution scale",
      expectedObservable:
        "Dragging Resolution scale to its maximum keeps the canvas responsive and updates backing pixel resolution without freezing pointer input.",
      fixture: "Resolution scale slider dragged from its minimum (1) to its maximum (2).",
      id: "render-scale-control-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: 2,
          metric: "numeric-max",
          smoothTarget: 2,
          smoothTargetRatio: 1,
          target: "canvas.renderScale",
          userFacingRange: "fully-guaranteed",
        },
        reason: "2 is the largest Resolution scale value the runtime exposes.",
        value: 2,
      },
      target: "canvas.renderScale",
      uiSelector: watercolorCanvasSelector,
      values: { default: 2, max: 2, min: 1 },
      workload: true,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    controlDragScenario({
      automatedTestName: "perf: paper-roughness-control-drag scenario is well-formed",
      browserTestName: "browser perf: roughness drag stays responsive",
      controlLabel: "Roughness",
      fixtureNote: "Roughness slider dragged from its minimum to its maximum value.",
      id: "paper-roughness-control-drag",
      target: "paper.roughness",
    }),
    controlDragScenario({
      automatedTestName: "perf: paper-relief-height-control-drag scenario is well-formed",
      browserTestName: "browser perf: relief height drag stays responsive",
      controlLabel: "Relief height",
      fixtureNote: "Relief height slider dragged from its minimum to its maximum value.",
      id: "paper-relief-height-control-drag",
      target: "paper.reliefHeight",
    }),
    controlDragScenario({
      automatedTestName: "perf: paper-drying-speed-control-drag scenario is well-formed",
      browserTestName: "browser perf: drying speed drag stays responsive",
      controlLabel: "Drying speed",
      fixtureNote: "Drying speed slider dragged from its minimum to its maximum value.",
      id: "paper-drying-speed-control-drag",
      target: "paper.dryingSpeed",
    }),
    controlDragScenario({
      automatedTestName: "perf: wetness-spread-control-drag scenario is well-formed",
      browserTestName: "browser perf: wetness spread drag stays responsive",
      controlLabel: "Wetness spread",
      fixtureNote: "Wetness spread slider dragged from its minimum to its maximum value.",
      id: "wetness-spread-control-drag",
      target: "dynamics.wetnessSpread",
    }),
    controlDragScenario({
      automatedTestName: "perf: granulation-control-drag scenario is well-formed",
      browserTestName: "browser perf: granulation drag stays responsive",
      controlLabel: "Granulation",
      fixtureNote: "Granulation slider dragged from its minimum to its maximum value.",
      id: "granulation-control-drag",
      target: "dynamics.granulation",
    }),
    controlDragScenario({
      automatedTestName: "perf: edge-darkening-control-drag scenario is well-formed",
      browserTestName: "browser perf: edge darkening drag stays responsive",
      controlLabel: "Edge darkening",
      fixtureNote: "Edge darkening slider dragged from its minimum to its maximum value.",
      id: "edge-darkening-control-drag",
      target: "dynamics.edgeDarkening",
    }),
    controlDragScenario({
      automatedTestName: "perf: pigment-opacity-control-drag scenario is well-formed",
      browserTestName: "browser perf: pigment opacity drag stays responsive",
      controlLabel: "Pigment opacity",
      fixtureNote: "Pigment opacity slider dragged from its minimum to its maximum value.",
      id: "pigment-opacity-control-drag",
      target: "dynamics.pigmentOpacity",
    }),
    controlChangeScenario({
      automatedTestName: "perf: pigment-swatch-control-change scenario is well-formed",
      browserTestName: "browser perf: pigment swatch selection stays responsive",
      expectedObservable:
        "Selecting a different pigment swatch applies to the next stroke without a noticeable delay or dropped frame.",
      fixtureNote: "Click a different pigment swatch.",
      id: "pigment-swatch-control-change",
      target: "paint.currentPigmentColor",
    }),
    controlChangeScenario({
      automatedTestName: "perf: brush-type-control-change scenario is well-formed",
      browserTestName: "browser perf: brush type selection stays responsive",
      expectedObservable:
        "Switching Brush type (Round/Filbert/Square) applies to the next stroke's stamp shape without a noticeable delay.",
      fixtureNote: "Click each Brush type option once.",
      id: "brush-type-control-change",
      target: "brush.type",
    }),
    controlChangeScenario({
      automatedTestName: "perf: hair-type-control-change scenario is well-formed",
      browserTestName: "browser perf: hair type selection stays responsive",
      expectedObservable:
        "Switching Hair type (Sable/Hog) applies to the next stroke's bristle noise without a noticeable delay.",
      fixtureNote: "Click each Hair type option once.",
      id: "hair-type-control-change",
      target: "brush.hairType",
    }),
    controlChangeScenario({
      automatedTestName: "perf: brush-water-refresh-control-change scenario is well-formed",
      browserTestName: "browser perf: refresh water action stays responsive",
      expectedObservable:
        "Clicking Refresh restores brush water charge to full without blocking the UI thread.",
      fixtureNote: "Click the Water section Refresh action.",
      id: "brush-water-refresh-control-change",
      target: "brush.waterCharge",
    }),
    controlChangeScenario({
      automatedTestName: "perf: mixing-area-control-change scenario is well-formed",
      browserTestName: "browser perf: mixing palette interactions stay responsive",
      expectedObservable:
        "Dragging in the mixing palette deposits pigment dabs and clicking samples a colour without blocking the UI thread.",
      fixtureNote: "Drag across the mixing palette, then click once to sample a colour.",
      id: "mixing-area-control-change",
      target: "paint.mixingArea",
      uiSelector: mixingAreaSelector,
    }),
    controlChangeScenario({
      automatedTestName: "perf: canvas-clear-control-change scenario is well-formed",
      browserTestName: "browser perf: clear painting action stays responsive",
      expectedObservable:
        "Clicking Clear wipes the painted simulation state back to blank paper without blocking the UI thread.",
      fixtureNote: "Paint a stroke, then click the Paper section Clear action.",
      id: "canvas-clear-control-change",
      target: "canvas.paintLayer",
    }),
    controlChangeScenario({
      automatedTestName: "perf: export-image-format-control-change scenario is well-formed",
      browserTestName: "browser perf: image export format selection stays responsive",
      expectedObservable:
        "Switching Image Export Format between PNG and JPEG updates the selection without blocking the UI thread.",
      fixtureNote: "Select each Image Export Format option once.",
      id: "export-image-format-control-change",
      target: "export.image.format",
    }),
    {
      automated: true,
      automatedTestName: "perf: export-resolution-control-change scenario is well-formed",
      browser: true,
      browserTestName: "browser perf: image export resolution selection stays responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 250 },
      expectedObservable:
        "Switching Image Export Resolution between 2K/4K/8K updates the selection without blocking the UI thread.",
      fixture: "Select each Image Export Resolution option once.",
      id: "export-resolution-control-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: "8k",
          metric: "custom",
          smoothTarget: "8k",
          smoothTargetRatio: 1,
          target: "export.image.resolution",
          userFacingRange: "fully-guaranteed",
        },
        reason: "8K is the largest Image Export resolution option the app exposes.",
        value: "8k",
      },
      target: "export.image.resolution",
      uiSelector: watercolorCanvasSelector,
      values: { default: "4k", max: "8k", min: "2k" },
      workload: true,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: canvas-width-control-change scenario is well-formed",
      browser: true,
      browserTestName: "browser perf: canvas width change stays responsive at max size",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 300 },
      expectedObservable:
        "Editing Canvas width to the largest working size resizes the simulation framebuffers and keeps the canvas responsive.",
      fixture: "Canvas width set to 3840, then a brush stroke is drawn.",
      id: "canvas-width-control-change",
      interaction: "control-change",
      stressFixture: {
        kind: "large-canvas",
        loadProfile: {
          hardLimit: 3840,
          metric: "numeric-max",
          smoothTarget: 3840,
          smoothTargetRatio: 1,
          target: "canvas.size.width",
          userFacingRange: "fully-guaranteed",
        },
        reason: "3840px is the largest working Canvas width used in this app's stress scenarios.",
        value: 3840,
      },
      target: "canvas.size.width",
      uiSelector: watercolorCanvasSelector,
      values: { default: 1920, max: 3840, min: 1920 },
      workload: true,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: canvas-height-control-change scenario is well-formed",
      browser: true,
      browserTestName: "browser perf: canvas height change stays responsive at max size",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 300 },
      expectedObservable:
        "Editing Canvas height to the largest working size resizes the simulation framebuffers and keeps the canvas responsive.",
      fixture: "Canvas height set to 2160, then a brush stroke is drawn.",
      id: "canvas-height-control-change",
      interaction: "control-change",
      stressFixture: {
        kind: "large-canvas",
        loadProfile: {
          hardLimit: 2160,
          metric: "numeric-max",
          smoothTarget: 2160,
          smoothTargetRatio: 1,
          target: "canvas.size.height",
          userFacingRange: "fully-guaranteed",
        },
        reason: "2160px is the largest working Canvas height used in this app's stress scenarios.",
        value: 2160,
      },
      target: "canvas.size.height",
      uiSelector: watercolorCanvasSelector,
      values: { default: 1080, max: 2160, min: 1080 },
      workload: true,
      workloadFixture: largeCanvasWorkloadFixture,
    },
    {
      automated: true,
      automatedTestName: "perf: watercolour-viewport-zoom-stress scenario is well-formed",
      browser: true,
      browserTestName: "browser perf: viewport zoom stays stable while painted",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 300, maxLongTaskMs: 220 },
      expectedObservable:
        "Zooming the canvas viewport in and out after painting a stroke keeps the stroke stable with no offset or scale jump, and simulation frames keep advancing.",
      fixture:
        "A stroke is painted at the large-canvas stress fixture, then the toolbar zoom in/out controls are used repeatedly.",
      id: "watercolour-viewport-zoom-stress",
      interaction: "viewport-zoom-stress",
      stress: true,
      stressFixture: {
        kind: "large-canvas",
        loadProfile: {
          hardLimit: { height: 2160, renderScale: 2, width: 3840 },
          metric: "canvas-area",
          smoothTarget: { height: 2160, renderScale: 2, width: 3840 },
          smoothTargetRatio: 1,
          target: "canvas.renderScale",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Reuses the largest working canvas size so zoom stress is measured under the heaviest simulation load.",
        value: { height: 2160, renderScale: 2, width: 3840 },
      },
      uiSelector: watercolorCanvasSelector,
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: watercolour-viewport-stability scenario is well-formed",
      browser: true,
      browserTestName: "browser perf: canvas viewport stays stable during painting",
      budget: { maxFrameGapMs: 120, maxLongTaskMs: 220 },
      expectedObservable:
        "Painting strokes and switching controls never changes canvas zoom, offset, or output dimensions unexpectedly.",
      fixture: "A stroke is painted while sampling canvas zoom/offset before and after.",
      id: "watercolour-viewport-stability",
      interaction: "viewport-stability",
      uiSelector: watercolorCanvasSelector,
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: watercolour-animation-viewport-drag scenario is well-formed",
      browser: true,
      browserTestName: "browser perf: viewport drag keeps simulation animating smoothly",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 300, maxLongTaskMs: 220 },
      expectedObservable:
        "Panning/dragging the canvas viewport while wet pigment is still drying keeps the simulation animating and does not change the user's painting or reset the canvas offset unexpectedly.",
      fixture: "A stroke is painted, then the canvas viewport is dragged/panned while the paint is still wet.",
      id: "watercolour-animation-viewport-drag",
      interaction: "animation-viewport-drag",
      stress: true,
      stressFixture: largeCanvasWorkloadFixture,
      uiSelector: watercolorCanvasSelector,
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: image-export-8k scenario is well-formed",
      browser: true,
      browserTestName: "browser perf: 8K export completes within budget",
      budget: { maxExportMs: 8000 },
      expectedObservable:
        "Exporting at 8K resolution resolves the Export PNG action, decodes to an image with the expected long-edge pixel dimension, and hides the sticky footer pending indicator.",
      fixture: "Image Export resolution set to 8K, then Export PNG is clicked.",
      id: "image-export-8k",
      interaction: "export-copy",
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: "8k",
          metric: "custom",
          smoothTarget: "8k",
          smoothTargetRatio: 1,
          target: "export.image.resolution",
          userFacingRange: "fully-guaranteed",
        },
        reason: "8K is the largest Image Export resolution option the app exposes.",
        value: "8k",
      },
      target: "export.image.resolution",
      values: { default: "4k", max: "8k", min: "2k" },
      workload: true,
    },
  ],
  usesCustomRenderer: true,
  workloadTargets: [
    "canvas.renderScale",
    "canvas.size.width",
    "canvas.size.height",
    "export.image.resolution",
    "brush.size",
  ],
});
